---
- name: Enable ssh on boot
  ansible.builtin.file:
    path: /boot/ssh
    state: touch
    mode: u=rw,g=r,o=r
  
- name: modifie the wpa configuration
  template:
    src: wpa-suplicant-conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
  tags: wpa-configuration

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 

- name: Change user password
  user:
    name: pi
    update_password: always
    password: "{{ new_password|password_hash('sha512') }}"

- name: Enable I2C
  command: raspi-config nonint do_i2c 1
  become: true

- name: Enable camera
  command: raspi-config nonint do_camera 1
  become: true
    